### ISSUE TITLE
sql error

### ISSUE THREAD

**Issue by yymmaa** [conan513/spp-legion-patch#8]
**Describe the bug**
world server not launching because error in both sql script

**To Reproduce**
1. Launcher_server.bat and chose 1 or 2

**Expected behavior**
server setup and showing me "now you ready to play"

**Screenshots**
non

**Additional context**
_2018_01_20_02_darkheart_thicket.sql_ : line **1282** 
```sql
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingDelta`, `VerifiedBuild`) VALUES ...
``` 
**probleme** : column `LevelScalingDelta` do not exists

_2018_08_05_04_world_quest.sql_ : line **1**
```sql
INSERT INTO creature (id, map, zoneId, areaId, position_x, position_y, position_z, orientation, spawntimesecs, curhealth) VALUES (11980, 530, 3520, 3939, -4206, 333, 119, 1.44, 600, 95000);
```
**probleme** : insert passed  but guid should not be 0, primary key violation

**Comment by wormogo** [comment]
It is advised to do a world db reset if you still have this problem.

Conan' comment: "Checking worldserver startup issue and recommend world database reset if failed."
